spring:
  application:
    name: Proyecto-Gestion-ventas

  datasource:
    url: jdbc:mysql://localhost:3306/VENTAAUTOSPERU
    username: root
    password: mysql

  jpa:
    properties:
      hibernate:
        dialect: 
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.hibertane.SQL: DEBUG
      org.hibernate.type: TRACE
server:
  port: 8080

config:
  security:
    keySecret: a599a5de-8045-4c1e-9bc2-5c1a5cee42a7
    jwt:
      expirationTime: 600000