spring:
  application:
    name: Proyecto-Gestion-ventas

  datasource:
    url: jdbc:mysql://localhost:3306/VENTAAUTOSPERU
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    level:
      org.hibertane.SQL: DEBUG
      org.hibernate.type: TRACE
server:
  port: 8081